language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - nosetests --with-coverage --cover-package=main
  
after_success:
  - coveralls

services:
 - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres 
