language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install nose
# command to run tests
script:
  - nosetests --with-coverage --cover-package=test
  - coverage report

after_success:
  - coveralls
